import type { Product } from "../types/product";

export function getProducts(): Product[] {
  return [
    {
      id: 1,
      name: "Picanha Bovina",
      category: "Bovinos",
      unit: "kg",
      salePrice: 59.9,
      stock: 12.5,
      minimumStock: 15,
      expirationDate: "2026-08-18",
    },
    {
      id: 2,
      name: "Contra Filé",
      category: "Bovinos",
      unit: "kg",
      salePrice: 49.9,
      stock: 18.2,
      minimumStock: 12,
      expirationDate: "2026-08-19",
    },
    {
      id: 3,
      name: "Alcatra",
      category: "Bovinos",
      unit: "kg",
      salePrice: 44.9,
      stock: 21.4,
      minimumStock: 15,
      expirationDate: "2026-08-20",
    },
    {
      id: 4,
      name: "Linguiça Toscana",
      category: "Embutidos",
      unit: "kg",
      salePrice: 34.9,
      stock: 8.3,
      minimumStock: 20,
      expirationDate: "2026-08-16",
    },
    {
      id: 5,
      name: "Coxa e Sobrecoxa",
      category: "Aves",
      unit: "kg",
      salePrice: 15.9,
      stock: 5.8,
      minimumStock: 15,
      expirationDate: "2026-08-14",
    },
    {
      id: 6,
      name: "Carne Moída",
      category: "Bovinos",
      unit: "kg",
      salePrice: 32.9,
      stock: 17.6,
      minimumStock: 18,
      expirationDate: "2026-08-15",
    },
    {
      id: 7,
      name: "Refrigerante 2L",
      category: "Mercearia",
      unit: "un",
      salePrice: 8.99,
      stock: 42,
      minimumStock: 20,
      expirationDate: null,
    },
    {
      id: 8,
      name: "Carvão 5kg",
      category: "Mercearia",
      unit: "pct",
      salePrice: 18.9,
      stock: 25,
      minimumStock: 10,
      expirationDate: null,
    },
  ];
}